openapi: 3.0.0
info:
  title: VNVNC API Gateway
  version: 1.0.0
paths:
  /api/{proxy+}:
    x-yc-apigateway-any-method:
      x-yc-apigateway-integration:
        type: cloud_functions
        function_id: d4ehafn3ofbigbqr3nsn
        service_account_id: auto
      parameters:
      - explode: false
        in: path
        name: proxy
        required: false
        schema:
          default: ''
          type: string
        style: simple
      summary: TicketsCloud Proxy
  /yandex-disk/{proxy+}:
    x-yc-apigateway-any-method:
      x-yc-apigateway-integration:
        type: cloud_functions
        function_id: d4epi3grr6a3nb6maug3
        service_account_id: auto
      parameters:
      - explode: false
        in: path
        name: proxy
        required: false
        schema:
          default: ''
          type: string
        style: simple
      summary: Yandex Disk Proxy
  /forms/{proxy+}:
    x-yc-apigateway-any-method:
      x-yc-apigateway-integration:
        type: cloud_functions
        function_id: d4e2qumbfs0s4q88bodd
        service_account_id: auto
      parameters:
      - explode: false
        in: path
        name: proxy
        required: false
        schema:
          default: ''
          type: string
        style: simple
      summary: Forms Handler